### ISSUE TITLE
Cannot open include file: 'boost/asio.hpp': No such file or directory

### ISSUE THREAD

**Issue by ipkstef** [jafarlihi/serpentine#1]
#pragma once

#include <string>
#include <boost/asio.hpp>  **<-- this doesn't exist** 

class Networking {
private:
	boost::asio::ip::tcp::socket* serverSocket;
	boost::asio::io_service *ios;
	Networking();
public:
	static Networking& getInstance();
	static void runPinger(boost::asio::io_service* ios, boost::asio::ip::tcp::socket* serverSocket);
	static void runReceiver(boost::asio::ip::tcp::socket* serverSocket);
	static void sendToServer(std::string message);
};

**Comment by jafarlihi** [comment]
You need to add Boost libraries to Visual Studio: https://www.boost.org/doc/libs/1_73_0/more/getting_started/windows.html
